service: node-ts-serverless
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ElementsTable", "Arn"] }

functions:
  createProduct:
    handler: src/functions.createProduct
    events:
      - httpApi:
          path: /elements
          method: post
  listProduct:
    handler: src/functions.listProduct
    events:
      - httpApi:
          path: /elements
          method: get
  getProduct:
    handler: src/functions.getProduct
    events:
      - httpApi:
          path: /elements/{id}
          method: get
  deleteProduct:
    handler: src/functions.deleteProduct
    events:
      - httpApi:
          path: /elements/{id}
          method: delete

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    ElementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ElementsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
