service: node-ts-serverless-quiz
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["GoogleForm", "Arn"] }

functions:
  createQuiz:
    handler: src/controller.createQuiz
    events:
      - http:
          path: /quiz
          method: post
          cors: true
  listQuiz:
    handler: src/controller.listQuiz
    events:
      - http:
          path: /quiz
          method: get
          cors: true
  deleteQuiz:
    handler: src/controller.deleteQuiz
    events:
      - http:
          path: /quiz/{id}
          method: delete
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    GoogleForm:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GoogleForm
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
